webpack-contrib/stylus-loader

- README.md
- package.json
Also include stylus and nib as test dependencies.
> Add instructions on how to test

- package.json
> update nib peer version to be less restrictive

- package.json
We were having some hardly caught race conditions and seems like it was because of old version of `when`.
So I upgraded it (our race condition is gone) and all other deps as well.
> Upgrade dependecies

- .testem.js
- .travis.yml
- package.json
- test/index.html
About time we got some CI testing in. :smile:
Runs tests with testem.
`npm run test-dev` for live reload test development.
> Travis ci testing with testem

- index.js
> Check for styl.sourcemap before assigning sourcesContent

- index.js
These changes should address the concerns brought up in #74. It wasn't clear to me the best way to add tests covering this. Let me know how you'd like me to proceed with that!
> Added support for Stylus's include and set.

- lib/listimports.js
- test/fixtures/imports/block-level.styl
- test/listimport.test.js
> Adds block-level imports to the import cache / webpack watcher

- index.js
- package.json
> Fix options mutation

- index.js
> webpack 4 doesn’t provide `this.options`

- LICENSE
- README.md
Ref https://github.com/shama/stylus-loader/issues/227
@evilebottnawi
> Transfer to webpack-contrib

- README.md
- package-lock.json
- package.json
- src/index.js
- test/loader.test.js
Extract stylus options in `options.stylusOptions`
Yse
No
> Extract stylus options

- README.md
- package-lock.json
- package.json
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/loader.test.js
- test/validate-options.test.js
Allow pass stylusOptions through function
No
No
> Allow pass stylusOptions through function

- README.md
- src/evaluator.js
- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/basic-nib.styl
- test/fixtures/import-unresolve.styl
- test/loader.test.js
> Refactor code

- README.md
- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/defineRaw.styl
- test/loader.test.js
- test/validate-options.test.js
`define raw` parameter processing
Fixes #229 
`stylusOptions.defined` now an array
No
> Feat: define raw parameter processing

- src/evaluator.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/node_modules/fakestylus/index.js
- test/fixtures/node_modules/fakestylus/main.styl
- test/fixtures/node_modules/fakestylus/package.json
- test/loader.test.js
> Feat: automatically resolve css files via package.json

- src/index.js
- test/loader.test.js
- test/validate-options.test.js
Fixes #237
Add compatibility with object syntax
No
No
> refactor: define option

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
- test/fixtures/bootstrap.styl
- test/fixtures/lib-bootstrap.styl
- test/loader.test.js
> Tes with bootstrap

- test/__snapshots__/loader.test.js.snap
- test/fixtures/alias/1.styl
- test/fixtures/alias/2.styl
- test/fixtures/import-webpack-alias.styl
- test/fixtures/web_modules/in-web-modules/index.styl
- test/helpers/getCompiler.js
- test/loader.test.js
Add tests for webpack resolver
No
No
> Add tests for webpack resolver

- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
Add tests for plugin using bootsrtap
Fixes #12 
No
No
> Add tests for bootstrap with plugin

- src/evaluator.js
- src/index.js
- src/utils.js
- test/__snapshots__/sourceMap-options.test.js.snap
- test/fixtures/source-map.styl
- test/sourceMap-options.test.js
Sourcemap.sources should contain absolute paths
Yes.
Sourcemap.sources now contain absolute paths
No
> Fix: sourcemap

- README.md
> docs: stylusOptions

- src/evaluator.js
- src/index.js
- src/lib/resolver.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/deep/deep-urls.styl
- test/loader.test.js
Fixes #103
Yes
`resolveUrl` option set to `true` by default
No
> Fix resolve url nocheck

- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-binop.styl
- test/fixtures/shallow-indent.styl
- test/helpers/index.js
- test/helpers/validateDependencies.js
- test/loader.test.js
> Add tests for indent import

- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-paths space.styl
- test/fixtures/paths with space/in-paths space.styl
- test/loader.test.js
Add test for paths with spaces
Fixes #205 
No
No
> Add test for paths with spaces

- bench/fixtures/imports/index.js
- bench/fixtures/imports/index.styl
- bench/fixtures/imports/testLoader.js
- bench/fixtures/imports/webpack.config.js
- bench/index.js
- package-lock.json
- package.json
> Test refactor bench

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
uncomment broken test on webpack@5
No
No
> test: uncomment test

- README.md
- src/evaluator.js
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
without nocheck stylus buggy, look at source code on the link on issue
No
less time compilation, no we don't check urls
> refactor: fix regression with url resolving

- test/__snapshots__/loader.test.js.snap
- test/fixtures/include-option.styl
- test/loader.test.js
> test: refactor

- src/evaluator.js
- src/index.js
change order of options
No
manually testing, need spy for tests, but it is unnecessary right now
> fix: resolving

- test/__snapshots__/loader.test.js.snap
- test/fixtures/(special$directory)/directoryfile.styl
- test/fixtures/(special$directory)/nested/nestedfile.styl
- test/fixtures/import-glob-special.styl
- test/loader.test.js
Test: special characters in path
No
No
> Test: special characters

- test/__snapshots__/loader.test.js.snap
- test/fixtures/deep/deep-literal.styl
- test/fixtures/empty-import.styl
- test/fixtures/import-unresolve-glob.styl
- test/fixtures/parse-error.styl
- test/fixtures/shallow-deep-literal.styl
- test/loader.test.js
> test: coverage

- test/fixtures/import-glob-alias.styl
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
- test/sourceMap-options.test.js
> Test refactor

- README.md
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/hoist-atrules.styl
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
Add support "hoistAtrules" option
No
No
> Feat: add support "hoistAtrules" option

- package-lock.json
- package.json
- src/utils.js
- test.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/glob-files/dir/a.styl
- test/fixtures/glob-files/dir/b.styl
- test/fixtures/glob-files/index.styl
- test/fixtures/import-glob.styl
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
> Fix resolving

- README.md
- jest.config.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
Add compress css in production mode
Compress css in production mode
No
> Feat: add compress css in production mode

- .gitignore
- test/__snapshots__/loader.test.js.snap
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
> test: update

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
Webpack resolve in import option
No
No
> Feat: webpack resolve in import option

- package-lock.json
- package.json
- src/index.js
converted relative paths to absolute paths in dependencies
No
No
> fix: converted relative paths to absolute paths in dependencies

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
- test/fixtures/import-glob-webpack.styl
- test/fixtures/import-webpack-prefer-relative.styl
- test/fixtures/import-webpack.styl
- test/fixtures/node_modules/prefer-relative/style.styl
- test/fixtures/prefer-relative/style.styl
- test/helpers/compile.js
- test/helpers/getCodeFromStylus.js
- test/helpers/getCompiler.js
- test/helpers/getErrors.js
- test/helpers/getWarnings.js
- test/helpers/normalizeErrors.js
- test/loader.test.js
> refactor: drop webpack@4

- README.md
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/implementation-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/implementation-option.test.js
- test/validate-options.test.js
`implementation` option added
No
No
> feat: implementation option added

- .github/workflows/nodejs.yml
Add node v18 to test workflow.
> chore: Add node v18 to test workflow

- README.md
> docs: close code block

- lint-staged.config.js
- src/index.js
- src/utils.js
- test/__snapshots__/implementation-option.test.js.snap
part of https://github.com/webpack/webpack/issues/15980
No
No
> fix: handling error better

- README.md
> docs: fix outdated broken links
