- index.js
Without this line, lines 49-52 never are executed. I think there is something bigger here going on, and I can investigate further, but this does resolve being able to define files that you'd like imported into all stylus files (i.e. nib) so that you don't need @import 'nib' all over the place.
> Allow for 'import' in webpack config

- index.js
Can be activated with `sourceMap` query parameter, e.g. `css?sourceMap!stylus?sourceMap`. Not using `this.sourceMap` (`devtool` config option) for reasons explained [here](https://github.com/webpack/css-loader/pull/40).
Closes #30.
> Add source maps support

- index.js
This solves two issues I ran into.
The first is that I wanted to pass sourcemap options directly to stylus for greater control over the output. This allows that, while defaulting to `stylus-loader?sourceMap => sourcemap = true`. 
The second is that when using css-loader and ExtractTextPlugin, you get two source map URLs in the output, one of which is to a nonexistant compiled .css file with the same name as your main stylus require. Since css-loader already inherits the source-map option from your webpack config, it seems that would make sense here too, and avoids the duplicate sourcemap issue, leaving only [name].css.map and a URL reference to it.
I think this is a possibly breaking change from 1.0.0 in the sense that `stylus-loader?sourceMap` currently results in `sourcemap = { comment: …
> pass through sourceMap option to stylus, and also inherit source-map option from devtool

- index.js
- lib/pathcache.js
Dependency lookup failed if the stylus source being compiled was different from what was written on disk (for example, if the source was already passed through a loader)
> Fixed dependency lookup for transformed sources

- .travis.yml
- lib/listimports.js
- test/all.js
- test/fixtures/imports/import.styl
- test/fixtures/imports/require.styl
- test/fixtures/imports/use.styl
- test/helpers/stylus-import-loader.js
- test/listimport.test.js
Picking up use calls in listimports we can pass those paths through PathCache and to webpack to list as dependencies.
This is an incomplete solution to #63. On the surface it fulfills watching a file mentioned by use. But it stops there. If that file further required another js file, that required file would not be watched.
Its a kind of funky too. Because this then lists a js file in the imports to PathCache, PatchCache will try to list imports of that js file, but it'll currently treat it as a stylus file, leading to an error, which listimports ignores as currently it leaves stylus to present errors as it'll do a better job. Since stylus treats the use('file') as js this ends up being fine but its kind of funky.
> Visit call expression to pick up use calls

- index.js
- lib/pathcache.js
- test/basic.test.js
Manual imports was overlooked a while ago when PathCache was added. Now with PathCache manual imports can be found like any other import and their dependencies can found and their path cached as well.
> Resolve manual imports with PathCache.resolvers

- index.js
- package.json
- test/basic.test.js
- test/fixtures/import-include.styl
- test/fixtures/include/in-include.styl
- test/webpack.config.js
Plugins are run as the first step in stylus rendering. Instead of passing plugins and running them there, we'll run them ourselves so when we resolve imports include side effects from those plugins take count. This lets depended on files take advantage of the paths those plugins include.
> Run plugins before resolving imports and files. Close #69

- package.json
Since stylus-loader depends on Stylus directly it's better to upgrade it from time-to-time.
> Upgrade Stylus

- index.js
When chained with other loaders, e.g. `css?sourceMap!postcss?...!stylus?sourceMap`, the displayed source map in the browser ends up being `null`, because the map passed down from `stylus-loader` doesn't contain the `sourcesContent` property.
Adding it allows the maps to be properly chained.
> add sourcesContent to returned source map

- lib/pathcache.js
hi - i think i've fixed the issue that @AwesomeJerry and @MikaelStenstrand were experiencing here: https://github.com/webpack/webpack/issues/1345
That is HMR not working on imported .styl files on Windows.
The problem was that the changed files were not being purged from webpack's CachedInputFileSystem.
readFile was being called with forward slashes causing webpack to store it in that state for comparison later on when file changes were detected. When webpack detected the changes it used backslashes instead so it never purged the file from it's cache.
The fix was just to normalize the resolved paths that were returned from Stylus.
> normalize resolved paths to fix watch/hmr on windows

- README.md
I had a difficult time tracking down the instructions to use `nib`. Figured it would be good to explicitly include in the readme.
> Instructions to enable nib

- index.js
Currently only the main, top-level source is added to the sourcemap, resulting in empty maps for any included files. This PR adds the missing sources from the cache. Fixes #56
> Add cached sources to sourcemap

- index.js
Recommended by webpack's documentation:
https://webpack.github.io/docs/how-to-write-a-loader.html#programmable-objects-as-query-option
Uses a different globalConfigCache for each configKey, just in case cache entries are somehow
different when the config is changed.
> Adds "config" query option to specify property on options object with stylus configs

- lib/evaluator.js
- lib/pathcache.js
- test/basic.test.js
- test/fixtures/context/a/color.styl
- test/fixtures/context/a/index.styl
- test/fixtures/context/b/color.styl
- test/fixtures/context/b/index.styl
- test/fixtures/context/index.styl
As #44 brings up, PathCache returns the same resolved path for two different contexts (folders). PathCache stores the resolved paths under the file that requested them. The right node could be looked up to find this filepath when the Evaluator is looking for the resolved path but it may be better to work the way utils.find does, with the context that contains the item importing the targets, not its filepath. This path is stored as the last member to this.paths, so this change passes that to PathCache and updates PathCache to take a directory path.
I've included a test that passes with the fix commit.
@cspotcode pointed out the problem well in #44.
> Specifically, this.paths is being used by Stylus's resolver to find files relative to the @import-ing file. The dirname of the @import-ing …
> Replace this.filename PathCache lookup with dirname

- README.md
- package.json
Since stylus-loader is not really depends on particular stylus
package version, it makes sense to remove it from the dependencies,
so a user could manually manage stylus version (upgrade, lock etc).
> Remove stylus from direct dependencies

- package.json
Users who upgrade to 2.0.0 who don't have stylus as a dependency will see errors when running webpack.
> Declare a peer dependency on stylus

- lib/pathcache.js
Modify PathCache's use of the webpack resolver to extract the path when used with webpack 2 and fall back to using the result as the path when the resolver returns a string.
> Fix PathCache for webpack 2

- index.js
In Node 6.x, all functions in the `path` module will throw an Error if the argument path is `undefined`. Previously it would silently return an empty string. This causes `stylus-loader` to error out due to `stylus`' sourcemap module trying to determine file path on `this.dest`.
This fix ensures `this.dest` is always a string and should preserve the same behavior as in Node 5.
> fix Node 6.x path erros for this.dest

- .travis.yml
- test/basic.test.js
- test/webpack.config.js
This is @phyllisstein's work in #119 with a minor change. I reverted changes to two tests that broke them. `stylus-loader` passes paths unchanged to stylus. To support the changed tests we'd need to make a breaking change to stylus-loader. I'd like to get the webpack testing in without that change first.
(Side note: likely such a change would instead be to add a new option since paths can also be defined in the webpack config and you then need to treat paths differently based on context of where the option came from, I think that'd be confusing.)
> Test on Webpack 1 and 2

- index.js
This commit forces the `forEach` callback to be bound to the stylus renderer instead of the global context.
Fixes #124
> fix: bind stylus renderer include function to itself

- index.js
```sh
./~/css-loader!./~/stylus-loader!./src/xxxx/index.styl
Module build failed: TypeError: use.forEach is not a function
at Object.module.exports (F:\xxxx\node_modules\stylus-loader\index.js:117:7)
@ ./src/xxxx/index.styl 4:14-124 13:2-17:4 14:20-130
```
happen on
```js
//...
stylus: {
include: paths,
use: function(render) { //... }
}
```
> Throw this error when `use` is only a function

- lib/pathcache.js
- test/basic.test.js
- test/fixtures/context/color.styl
When running stylus outside of stylus-loader it synchronously resolves
files while evaluating. While it evaluates as it imports a file, it
adds the context (its directory path) of that file to the stylus
instance's `paths` array. `paths` is used to look up relative paths by
iterating from the end of the array to the start.
`stylus-loader` since we added PathCache, left paths alone. This was an
oversight that leads to relative paths not working (unless stylus can't
find it and we fall back to resolving with webpack). `stylus-loader`
can't modify paths like stylus does since it can potentially resolve
multiple dependencies at once. We can concat and create separate
`paths` copies. This change does that by appending the context variable
that for stylus resolving PathCache was otherwise …
> Make PathCache stylus resolving a little more like stylus standalone

- README.md
- lib/pathcache.js
- test/basic.test.js
- test/fixtures/context/color.styl
Depends on #137
Let `stylus-loader` users opt for webpack resolving before stylus. This
can allow for most common stylus files to be found in parallel through
webpack's async resolver instead of blocking on file IO with stylus's
sync resolver.
> Add `preferPathResolver` option

- .travis.yml
- README.md
- index.js
- package.json
- test/webpack.config.js
- Add support for configuration being stored on `stylus` on the loader
context. With LoaderOptionsPlugin this helps with collisions that may
occur if you set the options key on the loader context with the
Plugin.
- Add convenience wrapper for LoaderOptionsPlugin.
> Add some help for configuring the loader with webpack 2

- index.js
For now, paths could only passed through query, it should also be allowed to pass it through global *stylusOptions*.
> add support to define *paths* through options

- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
Add loader options validation
No
No
> Add loader options validation

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
- test/validate-options.test.js
- test/webpackImporter-options.test.js
Add webpackImporter option
Fixes #117
No
No
> Feat: add webpackImporter option

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/additionalData-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/additionalData-option.test.js
- test/fixtures/additional-data.styl
- test/validate-options.test.js
Add additionalData option
Fixes #221 
No
No
> Feat: add additionalData option

- src/evaluator.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/deep/import-fakenib-binop.styl
- test/fixtures/import-binop.styl
- test/loader.test.js
> fix: import binop

- README.md
- src/index.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/prefix.styl
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
Add support "lineNumbers" option
No
No
> Feat: add support "lineNumbers" option

- src/index.js
- test/__snapshots__/sourceMap-options.test.js.snap
- test/fixtures/source-map/index.styl
- test/sourceMap-options.test.js
> fix: sourcemap

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
Nested webpack resolving in import option
No
No
> Feat: nested webpack resolving in import option

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/css-keyframe.css
- test/fixtures/import-webpack-css-keyframe.styl
- test/loader.test.js
> Fix: disallow searching for nested imports in css files

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
> fix: respect the `compress` option

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-package-with-exports-and-custom-condition.styl
- test/fixtures/node_modules/package-with-exports-and-custom-condition/index.cjs
- test/fixtures/node_modules/package-with-exports-and-custom-condition/index.js
- test/fixtures/node_modules/package-with-exports-and-custom-condition/package.json
- test/fixtures/node_modules/package-with-exports-and-custom-condition/style-1.styl
- test/fixtures/node_modules/package-with-exports-and-custom-condition/style-2.styl
- test/helpers/getCodeFromStylus.js
- test/loader.test.js
> feat: allow to extend `conditionNames`

- package.json
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/sourceMap-options.test.js.snap
- test/loader.test.js
- test/sourceMap-options.test.js
Better perf and less deps
No
Added test which allow to override source map options, I think we need to implement this for other CSS like loaders, but it will be separately
> fix(perf): avoud using `clona` for `stylus` options

- README.md
> docs: correct type definitions of `include` and `import` (close: #420)
